### ISSUE TITLE
Channel 

### ISSUE THREAD

**Issue by jiuker** [pragmagic/vscode-nim#166] opened 2020-06-16 05:16 UTC
undeclared identifier: 'Channel'

**Comment by RSDuck** [comment] 2020-06-16 08:49
please be more descriptive with your issues. The only reason we can know what you mean, is because this is a common issue.

You need to make a [nimscript file for nim check and nim suggest to pickup the threads option](https://github.com/pragmagic/vscode-nim/issues/98).

**Comment by serge-hulne** [comment] 2020-07-29 19:09
I've seen the same bug in vscode-nim 
- Windows 10.
- Nim O.66
![Screenshot (642)](https://user-images.githubusercontent.com/303502/88842458-c74f5a00-d1df-11ea-884b-2fe41e59e7a3.png)

**Comment by Yardanico** [comment] 2020-07-30 06:38
That's not a VSCode bug, you need to provide configuration for Nim (and Nimsuggest since it uses the compiler) for it to understand that you're actually using threads.

There are mainly 2 ways - with older .nim.cfg and newer .nims, but the syntax for simple options is the same.
E.g. make a file named `as1.nims` or `as1.nim.cfg` or `config.nims` (that'll apply to all .nim files in the same directory) or `nim.cfg` (same as with `config.nims` but older format) with contents:
```
--threads:on
```

And then Nimsuggest will actually recognize that you're using threads.

**Comment by Yardanico** [comment] 2020-07-30 06:39
Also yeah, as @RSDuck said this is a duplicate of https://github.com/pragmagic/vscode-nim/issues/98 and https://github.com/pragmagic/vscode-nim/issues/70 and should be closed.

**Comment by serge-hulne** [comment] 2020-07-30 06:41
Thanks.

**Comment by serge-hulne** [comment] 2020-07-30 09:29
I commented on the issue, I didn't raise it, but yes it should be closed.

**Closed** 2024-01-26 08:29 UTC
