### ISSUE TITLE
VSCode workspace not being parsed correctly for Nim suggest

### ISSUE THREAD

**Issue by pr-yemibedu** [pragmagic/vscode-nim#106] opened 2018-11-07 23:16 UTC
Hello,
 Looking at line [NimUtil Line 51](https://github.com/pragmagic/vscode-nim/blob/0142ce7d452be9f84e51949482ce0a874ae16e27/src/nimUtils.ts#L51) I see that the **toLocalFile** function is suppose to do a merge of workspace and filepath. This is causing an error that the project root folder name is being counted twice. NimSuggest is failing because of this.

With base folder _*add*_ being put in a workspace this is what happens:
  -  Expected result : e:\projects\nim\add\src\add.nim
  -  Given result : e:\projects\nim\add\add\src\add.nim

The exact error message: **"console.ts:136 [Extension Host] Nimsuggest returns unknown port number: cannot find file: e:\projects\nim\add\add\src\add.nim"**

There should be another check inside that if the final path is not valid to return something else or report an error. Thank you. Good day.

**Comment by kosz78** [comment] 2018-11-12 16:09
@pr-yemibedu I cant reproduce this behavior, could You please provide example project?

**Comment by pr-yemibedu** [comment] 2018-11-12 17:06
Hello,
 I have put together my problem project that shows my issue (C zip) and a new one without the issue (N zip). They have a workspace over a lib and a bin. opening just the lib in VSCode will provide type information after a few seconds. 
  - [c.zip](https://github.com/pragmagic/vscode-nim/files/2572836/c.zip) and [n.zip](https://github.com/pragmagic/vscode-nim/files/2572753/n.zip)

 The workspace of **C** never gets passed the **`Indexing: #` state**. Not sure what the cause would be as the only difference is an additional ".workspace" file at the root. Thank you. Good day.

**Comment by kosz78** [comment] 2018-12-01 16:36
Fixed in 805d3f1

**Closed by kosz78** 2018-12-01 16:36 UTC
